### ISSUE TITLE
Randomly occuring NullPointerException

### ISSUE THREAD

**Issue by moqmar** [M4lik/burning-series#3]
See screenshot for details, the app crashes without any error popup (I guess there should be one from the system normally?! :confused:)

![screenshot_20170123-193135_01_01](https://cloud.githubusercontent.com/assets/5559994/22217323/cfd20050-e1a2-11e6-90b9-f7f3aa285938.png)

**Comment by M4lik** [comment]
this is caused by an inconvenient way to implement the search functionality. started working on it.

**Comment by M4lik** [comment]
done! 😄
